
CREATE CACHED TABLE "PUBLIC"."MUSIC_GENRE"(
                                        "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
                                        "NAME" VARCHAR(255)
);

ALTER TABLE "PUBLIC"."MUSIC_GENRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_12" UNIQUE("NAME");

-- create join table disc/music genre
CREATE CACHED TABLE "PUBLIC"."DISC_MUSIC_GENRE"(
                                                        "DISC_ID" BIGINT NOT NULL,
                                                        "MUSIC_GENRE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DISC_MUSIC_GENRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_13" PRIMARY KEY("DISC_ID", "MUSIC_GENRE_ID");

ALTER TABLE "PUBLIC"."DISC_GENRES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_15" FOREIGN KEY("GENRES_ID")
    REFERENCES "PUBLIC"."MUSIC_GENRE"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DISC_GENRES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_16" FOREIGN KEY("DISC_ID")
    REFERENCES "PUBLIC"."DISC"("ID") NOCHECK;

