CREATE USER IF NOT EXISTS "SA" SALT '73bfeda0485d6f43' HASH '52f240557786bae1b7df1adc07f0e8d95571d68961f1dc6e52f27fc51c565c61' ADMIN;
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;

CREATE CACHED TABLE "PUBLIC"."ARTIST"(
    "ID" BIGINT NOT NULL,
    "COMMENT" CLOB,
    "MB_IDENTIFIER" VARCHAR(255),
    "NAME" VARCHAR(255),
    "ROLE" VARCHAR(255),
    "TYPE" INTEGER
);

ALTER TABLE "PUBLIC"."ARTIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");

CREATE CACHED TABLE "PUBLIC"."CATALOGUE"(
    "ID" BIGINT NOT NULL,
    "COMMENT" CLOB,
    "NAME" VARCHAR(255)
);

ALTER TABLE "PUBLIC"."CATALOGUE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");

CREATE CACHED TABLE "PUBLIC"."CATALOGUE_DISCS"(
    "CATALOGUE_ID" BIGINT NOT NULL,
    "DISCS_ID" BIGINT NOT NULL
);

CREATE CACHED TABLE "PUBLIC"."DISC"(
    "ID" BIGINT NOT NULL,
    "COMMENT" CLOB,
    "NAME" VARCHAR(255),
    "PATH_TO_IMAGE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."DISC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."DISC_CREDITED_ARTISTS"(
    "DISC_ID" BIGINT NOT NULL,
    "CREDITED_ARTISTS_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DISC_CREDITED_ARTISTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("DISC_ID", "CREDITED_ARTISTS_ID");
CREATE CACHED TABLE "PUBLIC"."DISC_EXTERNAL_IDENTIFIER"(
    "DISC_ID" BIGINT NOT NULL,
    "EXTERNAL_IDENTIFIER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DISC_EXTERNAL_IDENTIFIER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("DISC_ID", "EXTERNAL_IDENTIFIER_ID");
CREATE CACHED TABLE "PUBLIC"."DISC_RELATED_ARTIST"(
    "DISC_ID" BIGINT NOT NULL,
    "RELATED_ARTIST_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DISC_RELATED_ARTIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("DISC_ID", "RELATED_ARTIST_ID");
CREATE CACHED TABLE "PUBLIC"."DISC_TRACKS"(
    "DISC_ID" BIGINT NOT NULL,
    "TRACKS_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DISC_TRACKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("DISC_ID", "TRACKS_ID");
CREATE CACHED TABLE "PUBLIC"."EXTERNAL_IDENTIFIER"(
    "ID" BIGINT NOT NULL,
    "IDENTIFIER" VARCHAR(255),
    "TYPE" INTEGER
);
ALTER TABLE "PUBLIC"."EXTERNAL_IDENTIFIER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."TRACK"(
    "ID" BIGINT NOT NULL,
    "COMMENT" CLOB,
    "DURATION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "NUMBER" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."TRACK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."USER_CONFIGURATION"(
    "ID" BIGINT NOT NULL,
    "KEY" VARCHAR(255),
    "VALUE" VARCHAR(255)
);

ALTER TABLE "PUBLIC"."USER_CONFIGURATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_10" PRIMARY KEY("ID");

ALTER TABLE "PUBLIC"."DISC_TRACKS" ADD CONSTRAINT "PUBLIC"."UK_FCLMMIP0UY1SQKTLASQ5Y6XHA" UNIQUE("TRACKS_ID");
ALTER TABLE "PUBLIC"."USER_CONFIGURATION" ADD CONSTRAINT "PUBLIC"."UK_FRVEXXU33VR8X8SLOUMQGHXFC" UNIQUE("KEY");
ALTER TABLE "PUBLIC"."DISC_EXTERNAL_IDENTIFIER" ADD CONSTRAINT "PUBLIC"."UK_NF09SEI96DBY6YJ26DGUGJ5GM" UNIQUE("EXTERNAL_IDENTIFIER_ID");
ALTER TABLE "PUBLIC"."CATALOGUE" ADD CONSTRAINT "PUBLIC"."UK_2OVIEVHTVLM9LUCN4B2XIF8IK" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."CATALOGUE_DISCS" ADD CONSTRAINT "PUBLIC"."UK_LKK901UQNPSH48TGF93YIRP2S" UNIQUE("DISCS_ID");
ALTER TABLE "PUBLIC"."DISC_CREDITED_ARTISTS" ADD CONSTRAINT "PUBLIC"."FKSAV5DF0FPM7WPBD6OPBHO5POJ" FOREIGN KEY("CREDITED_ARTISTS_ID") REFERENCES "PUBLIC"."ARTIST"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_TRACKS" ADD CONSTRAINT "PUBLIC"."FK2N3AKMYS2WSY4GFC4A2O2P34X" FOREIGN KEY("DISC_ID") REFERENCES "PUBLIC"."DISC"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CATALOGUE_DISCS" ADD CONSTRAINT "PUBLIC"."FKI9BSRELNK4SCQAQMOXHRNK0UA" FOREIGN KEY("CATALOGUE_ID") REFERENCES "PUBLIC"."CATALOGUE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CATALOGUE_DISCS" ADD CONSTRAINT "PUBLIC"."FKI20DJA6F4OB8TIM0970XYDP03" FOREIGN KEY("DISCS_ID") REFERENCES "PUBLIC"."DISC"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_RELATED_ARTIST" ADD CONSTRAINT "PUBLIC"."FKIGPYSP2162DXO1KJBIQPGY6IQ" FOREIGN KEY("RELATED_ARTIST_ID") REFERENCES "PUBLIC"."ARTIST"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_TRACKS" ADD CONSTRAINT "PUBLIC"."FKMT2SOFHIB6YVF1DJKEJ19UANT" FOREIGN KEY("TRACKS_ID") REFERENCES "PUBLIC"."TRACK"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_CREDITED_ARTISTS" ADD CONSTRAINT "PUBLIC"."FK5WE8457FUX052R5EPCBQ2CIAK" FOREIGN KEY("DISC_ID") REFERENCES "PUBLIC"."DISC"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_RELATED_ARTIST" ADD CONSTRAINT "PUBLIC"."FKJBJO9AMCDH7EFVUKF1T4D1244" FOREIGN KEY("DISC_ID") REFERENCES "PUBLIC"."DISC"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_EXTERNAL_IDENTIFIER" ADD CONSTRAINT "PUBLIC"."FKH81YP95ECDT54ONPXV6ORU4KL" FOREIGN KEY("EXTERNAL_IDENTIFIER_ID") REFERENCES "PUBLIC"."EXTERNAL_IDENTIFIER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DISC_EXTERNAL_IDENTIFIER" ADD CONSTRAINT "PUBLIC"."FK7T0YGW8OXFVFVF39B9GH371B0" FOREIGN KEY("DISC_ID") REFERENCES "PUBLIC"."DISC"("ID") NOCHECK;