@startuml

package "View JavaFX" as Front {

}


package "Model" as Model{
'Entities definition
 class Disc
 class Catalogue
 class Artist
 class Band
 class Track

'Relationships
  Disc }o- Catalogue
  Disc }o- Band
  Band -o{ Artist
  Disc -|{ Track
}

database DB [
  DB
]

    Front --> Model
    Model --> DB

@enduml