@startuml

left to right direction
package view{
class View_A {}
class View_B  {}
}

package model{
class Model_X{}
class Model_Y{}
}
package controller {
class Controller_A{}
class Controller_B{}
}

package DataService:@Transactional as service {
class service_T
class service_Q
}

Controller_A<-->Controller_B: "if needed"
Controller_A-->View_A : manages
Controller_B-->View_B : manages
View_A-->Controller_A: requests actions
View_B-->Controller_B: requests actions

controller<-->service: fetch/save
service<-->model

@enduml